# **Pytorch Tutorial**


In [ ]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [ ]:
x = torch.randn(4,5)
#表示4*5的tensor
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-0.2472,  0.1501,  0.4581,  1.6551, -1.1455],
        [ 1.2600, -1.6655, -0.2677, -1.3516,  0.3594],
        [-1.0189, -0.5542,  0.3540,  0.6980,  0.0261],
        [ 0.1906,  1.7242,  1.0288,  0.2250, -1.2048]])
tensor([[ 0.4776, -0.3648, -1.6535, -0.9661, -0.1081],
        [ 0.3834, -1.7931, -1.4176,  2.4008, -0.2281],
        [ 0.5163,  0.7463,  2.8462,  0.5865,  1.0020],
        [-0.9588,  0.7482,  0.4056, -1.1182, -1.4378]])
tensor([[-1.1572e+00, -2.3009e+00,  1.7841e+00,  2.3465e-01,  1.2551e+00],
        [ 2.1620e-03, -2.0426e+00, -4.6076e-01,  5.9458e-01,  4.3331e-01],
        [ 6.0431e-01, -5.8488e-01,  7.5610e-02,  1.7736e+00, -7.0731e-02],
        [-2.7863e-01,  1.2080e-02, -9.5016e-01,  5.7351e-01, -3.5174e-01]])


In [ ]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
#找到x裡面的最大值
# https://blog.csdn.net/qq_27261889/article/details/88613932
# https://blog.csdn.net/Z_lbj/article/details/79766690
print(m)

tensor(1.7242)


In [ ]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
# keepdim 表示是否需要保持输出的维度与输入一样，keepdim=True表示输出和输入的维度一样，keepdim=False表示输出的维度被压缩了，也就是输出会比输入低一个维度。
m, idx = torch.max(x,0)
# m是找出x裡面每一列(第0維度)的最大值 , 第1維度(dim=1)
# 用 torch.size去想 , [4,5]>先創建4行,再填入5個數值 dim=0時>先看行再找列的值 , dim=1時>先看列再找行的數值
print(m)
# 最大值分別在哪一個list(index)
print(idx)

tensor([1.2600, 1.7242, 1.0288, 1.6551, 0.3594])
tensor([1, 3, 3, 0, 1])


In [ ]:
# 2-2 同上
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([ 0.8775,  1.4307,  0.6310, -0.4453,  1.2551])
tensor([3, 1, 1, 3, 1])


In [ ]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([ 0.8775,  1.4307,  0.6310, -0.4453,  1.2551])
tensor([3, 1, 1, 3, 1])


In [ ]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[1.7620, 0.5362, 1.6590, 0.7993, 0.6732]])
tensor([[1, 1, 3, 3, 2]])


In [ ]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([1.2600, 1.7242, 1.0288, 1.6551, 0.3594])
tensor([1, 3, 3, 0, 1])


In [ ]:
# 2-6
p = (m,idx)
m, idx = torch.max(x,0,False,p)
# wrong : *out is a keyword argument(關鍵字參數)
print(p[0])
print(p[1])

TypeError: ignored

In [ ]:
# 2-7
m, idx = torch.max(x,True)
# wring : *did not specify(指定) dim
print(m)
print(idx)

tensor([[1.2600, 1.7242, 1.0288, 1.6551, 0.3594]])
tensor([[1, 3, 3, 0, 1]])


In [ ]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
# x,y兩個tensor逐一值做比較,取大者
t = torch.max(x,y)
print(t)

tensor([[ 0.4776,  0.1501,  0.4581,  1.6551, -0.1081],
        [ 1.2600, -1.6655, -0.2677,  2.4008,  0.3594],
        [ 0.5163,  0.7463,  2.8462,  0.6980,  1.0020],
        [ 0.1906,  1.7242,  1.0288,  0.2250, -1.2048]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [ ]:
# 1. different device error

# wrong test : model and x not the sane device
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

torch.Size([1])


In [ ]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [ ]:
# 2. mismatched dimensions(尺寸不匹配) error
# 兩個tensor要做相加,他們的維度尺寸必須要相同
x = torch.randn(4,5)
y = torch.randn(5,4)
z = x + y

RuntimeError: ignored

In [ ]:
# 2. mismatched dimensions error (fixed)
# 延續上面,把y做transpose(轉置)>維度對調 >> 就會和x的維度尺寸相同
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


CUDA out of memory. Tried to allocate(分配) 350.00 MiB (GPU 0; 14.76 GiB total
capacity; 11.94 GiB already allocated(分配); 123.75 MiB free; 13.71 GiB reserved in
total by PyTorch)
=> The batch size of data is too large to fit in the GPU. Reduce the batch size.

In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


RuntimeError: ignored

If the data is iterated (batch size = 1), the problem will be solved. You can also
use DataLoader

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  #Squeeze: remove the specified dimension with length = 1 , squeeze = 0 > 把第0維度的資料拿掉(會降維)
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0]) 
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: ignored

expected(預期的) scalar(純量) type Long but found Float
=> labels must be long tensors, cast it to type “Long” to fix this issue

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
print(labels)
lossval = L(outs,labels)
print(lossval)

tensor([1, 2, 3, 4, 0])
tensor(2.7175)


**3. More on dataset and dataloader**


A dataset is a cluster(叢集) of data in a organized(有組織的) way. A dataloader is a loader which can iterate(迭代) through(通過) the data set.

Let a dataset be the English alphabets(字母表) "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle(洗牌) the data. This is where torch.utils.data.DataLoader comes in handy(便利). If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two imformation to fulfill(實現) its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding(
相應的) data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data? 
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['k']
['l']
['h']
['o']
['v']
['f']
['p']
['i']
['b']
['u']
['e']
['t']
['y']
['x']
['d']
['q']
['j']
['c']
['m']
['s']
['w']
['r']
['z']
['n']
['g']
['a']


A simple data augmentation technique(技術) can be done by changing the code in `__len__()` and `__getitem__()`. Suppose(假設) we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
# 這裡在做資料強化,把一些小寫字母 > 大寫 來增加資料量
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['C']
['O']
['s']
['n']
['v']
['p']
['j']
['a']
['r']
['T']
['F']
['H']
['b']
['X']
['R']
['Z']
['U']
['W']
['w']
['E']
['m']
['K']
['G']
['l']
['D']
['z']
['Q']
['g']
['q']
['i']
['Y']
['c']
['P']
['A']
['B']
['S']
['I']
['M']
['o']
['d']
['y']
['t']
['L']
['V']
['e']
['J']
['h']
['x']
['N']
['u']
['k']
['f']
